defmodule PdfElixide.Native do
  @moduledoc false

  mix_config = Mix.Project.config()
  version = mix_config[:version]
  github_url = mix_config[:package][:links]["Source"]

  opts = [
    otp_app: :pdf_elixide,
    crate: :pdf_elixide_nif,
    base_url: "#{github_url}/releases/download/v#{version}",
    version: version
  ]

  opts =
    if System.get_env("PDF_ELIXIDE_BUILD") in ["1", "true"] do
      Keyword.put(opts, :force_build, true)
    else
      opts
    end

  use RustlerPrecompiled, opts

  def document_open(_path, _options), do: err()
  def document_from_bytes(_bytes, _options), do: err()
  def document_close(_doc), do: err()
  def document_closed(_doc), do: err()
  def document_page_count(_doc), do: err()
  def document_has_structure_tree(_doc), do: err()
  def document_has_xfa(_doc), do: err()
  def document_is_encrypted(_doc), do: err()
  def document_authenticate(_doc, _password), do: err()
  def document_extract_text(_doc, _page_index, _options), do: err()
  def document_extract_all_text(_doc, _options), do: err()
  def document_to_markdown(_doc, _page_index, _options), do: err()
  def document_to_markdown_all(_doc, _options), do: err()
  def document_to_markdown_to_dir(_doc, _page_index, _options), do: err()
  def document_to_markdown_all_to_dir(_doc, _options), do: err()
  def document_to_html(_doc, _page_index, _options), do: err()
  def document_to_html_all(_doc, _options), do: err()
  def document_to_html_to_dir(_doc, _page_index, _options), do: err()
  def document_to_html_all_to_dir(_doc, _options), do: err()
  def document_words(_doc, _page_index, _options), do: err()
  def document_all_words(_doc, _options), do: err()
  def document_text_lines(_doc, _page_index, _options), do: err()
  def document_all_text_lines(_doc, _options), do: err()
  def document_chars(_doc, _page_index, _options), do: err()
  def document_all_chars(_doc, _options), do: err()
  def document_spans(_doc, _page_index, _options), do: err()
  def document_all_spans(_doc, _options), do: err()
  def document_tables(_doc, _page_index, _options), do: err()
  def document_all_tables(_doc, _options), do: err()
  def table_to_markdown(_table, _options), do: err()
  def table_to_html(_table), do: err()
  def table_to_text(_table), do: err()
  def table_close(_table), do: err()
  def table_closed(_table), do: err()
  def document_paths(_doc, _page_index), do: err()
  def document_all_paths(_doc), do: err()
  def document_rects(_doc, _page_index), do: err()
  def document_all_rects(_doc), do: err()
  def document_lines(_doc, _page_index), do: err()
  def document_all_lines(_doc), do: err()
  def document_search(_doc, _pattern, _page_index, _options), do: err()
  def document_all_search(_doc, _pattern, _options), do: err()
  def document_prepare_search(_doc), do: err()
  def document_clear_search_index(_doc), do: err()
  def document_fonts(_doc, _page_index), do: err()
  def document_all_fonts(_doc), do: err()
  def font_data(_font), do: err()
  def font_close(_font), do: err()
  def font_closed(_font), do: err()
  def document_outline(_doc), do: err()
  def document_annotations(_doc, _page_index), do: err()
  def document_all_annotations(_doc), do: err()
  def document_images(_doc, _page_index), do: err()
  def document_all_images(_doc), do: err()
  def image_to_binary(_image, _format), do: err()
  def image_save(_image, _path, _format), do: err()
  def image_data(_image), do: err()
  def image_close(_image), do: err()
  def image_closed(_image), do: err()
  def document_get_page_media_box(_doc, _page_index), do: err()
  def document_get_page_rotation(_doc, _page_index), do: err()
  def document_has_text_layer(_doc, _page_index), do: err()
  def document_form_fields(_doc), do: err()
  def document_signatures(_doc), do: err()
  def document_unsigned_signature_fields(_doc), do: err()
  def document_signature_count(_doc), do: err()
  def document_dss(_doc), do: err()
  def document_info(_doc), do: err()
  def document_xmp_metadata(_doc), do: err()
  def document_permissions(_doc), do: err()
  def document_page_labels(_doc), do: err()
  def document_page_label(_doc, _page_index), do: err()
  def document_layers(_doc), do: err()
  def document_page_inks(_doc, _page_index, _options), do: err()

  def editor_open(_path), do: err()
  def editor_from_bytes(_bytes), do: err()
  def editor_close(_editor), do: err()
  def editor_closed(_editor), do: err()
  def editor_page_count(_editor), do: err()
  def editor_is_modified(_editor), do: err()
  def editor_form_fields(_editor), do: err()
  def editor_signatures(_editor), do: err()
  def editor_unsigned_signature_fields(_editor), do: err()
  def editor_signature_count(_editor), do: err()
  def editor_dss(_editor), do: err()
  def editor_set_form_field_value(_editor, _name, _value), do: err()
  def editor_to_bytes(_editor, _options), do: err()
  def editor_save(_editor, _path, _options), do: err()
  def editor_flatten_forms(_editor), do: err()
  def editor_flatten_forms_on_page(_editor, _page_index), do: err()
  def editor_flatten_all_annotations(_editor), do: err()
  def editor_flatten_page_annotations(_editor, _page_index), do: err()
  def editor_flatten_warnings(_editor), do: err()

  def signature_verify_detached(_contents, _byte_range, _pdf_data), do: err()
  def signature_verify_signer(_contents), do: err()
  def signature_certificate(_contents), do: err()
  def signature_signing_time(_signing_time), do: err()
  def signature_pades_level(_contents, _dss), do: err()
  def signature_document_timestamp(_pdf_data), do: err()
  def signature_timestamp(_contents), do: err()
  def signature_verify_timestamp(_contents), do: err()
  def signature_verify_document_timestamp(_contents, _byte_range, _pdf_data), do: err()
  def timestamp_parse(_token), do: err()
  def timestamp_verify(_token), do: err()

  def log_set_level(_level), do: err()
  def log_drain, do: err()
  def log_pending, do: err()
  def log_enabled, do: err()

  defp err, do: :erlang.nif_error(:nif_not_loaded)
end
