defmodule PdfElixide.Native.InventoryTest do
  @moduledoc false
  use ExUnit.Case, async: true

  # Generated by Rustler rather than backed by registered NIFs.
  @generated [rustler_init: 0, load_rustler_precompiled: 0]

  setup_all do
    assert File.dir?(PdfElixide.NifSource.src_dir()),
           "NIF sources not found at #{PdfElixide.NifSource.src_dir()}"

    nifs = for nif <- PdfElixide.NifSource.nifs(), do: {String.to_atom(nif.name), nif.arity}

    # Not `registered:` — ExUnit reserves that context key for
    # `register_attribute/3` and silently overwrites the value with its own map.
    {:ok, nifs: nifs, stubs: PdfElixide.Native.__info__(:functions) -- @generated}
  end

  test "every registered NIF has a stub", %{nifs: nifs, stubs: stubs} do
    missing = nifs -- stubs

    assert missing == [],
           """
           These NIFs were parsed out of the crate but have no matching function in
           `PdfElixide.Native`. A genuinely missing stub would have kept the
           library from loading at all, so reaching this assertion most likely
           means `PdfElixide.NifSource` read a name or arity wrongly. Check that
           first, then add the stub:

           #{format(missing)}
           """
  end

  test "every stub is backed by a registered NIF", %{nifs: nifs, stubs: stubs} do
    stray = stubs -- nifs

    assert stray == [],
           """
           These functions in `PdfElixide.Native` have no `#[rustler::nif]` behind
           them, so they stay stubs after the library loads and report
           `:nif_not_loaded` — which `Wrap.call/1` hands back as an ordinary
           `%PdfElixide.Error{reason: :other}`. Remove each, or fix the name or
           arity it was meant to match:

           #{format(stray)}
           """
  end

  defp format(entries) do
    Enum.map_join(entries, "\n", fn {name, arity} -> "  - #{name}/#{arity}" end)
  end
end
